blank_issues_enabled: true
contact_links:
  - name: ğŸ‘©â€ğŸ’» Join the WalkingPal Discord community
    url: https://discord.gg/Et3aQTsW6a
    about: If you need help or if you want to to discuss/ask questions, join the WalkingPal Discord community!
  